/* DOCUMENT INFORMATION
	- Document: ZuniSport Web Project
	- Version:  1.0
	- Author:   Azeroglu Emin
*/

Language = {
    /* English */
    en: {
        currentTime: 'CURRENT TIME',
        myTournamentsHead: 'MY TOURNAMENTS',
        myTournamentsText: 'To select your leagues, just click the <i class="icon icon-top-favourite-selected"></i>  icon located next to the name ofthe league.',
        myTeamsHead: 'MY TEAMS',
        myTeamsText: 'To select your leagues, just click the <i class="icon icon-top-favourite-selected"></i>  icon located next to the name ofthe team.',
        tabAllGames: 'All Games',
        tabFinished: 'Finished',
        tabScheduled: 'Scheduled',
        tabLive: 'Live',
        tabMyGames: 'My Games',
        loginGuest: 'Guest',
        loginButton: 'Login',
        predictionsHead: 'Predictions',
        footerText: '<p>Football live scores on Zunisport has live coverage from more than 500 worldwide soccer leagues, cups and tournaments with live updated results, statistics, league tables, fixtures and live streaming.</p>' +
        '<p>Live matches from all football leagues have fast and accurate updates for minutes, scores, halftime and full time soccer results, goal scorers and assistants, cards, substitutions, match statistics and live stream. Zunisport has details for each team where you can see last 10 soccer matches, tables, fixtures, results, statistics and much more. Also, all scores on Zunisport livescore are automatically updated and you don\'t need to refresh it manually. With adding football matches or teams you want to follow in favorites, following your matches or teams livescores, results and statistics will be even more simple. There is an option to select All or Live football matches.</p>',
        portalSelectionHead: 'Select your portal',
        month1: 'January',
        month2: 'February',
        month3: 'March',
        month4: 'April',
        month5: 'May',
        month6: 'June',
        month7: 'July',
        month8: 'August',
        month9: 'September',
        month10: 'October',
        month11: 'November',
        month12: 'December',
        txtPrNoNewMatch: 'There is no new match',
        txtPrNoWinMatch: 'There is no win match',
        txtPrNoLoseMatch: 'There is no lose match',
        liveNodata: 'There is no live match',
        matchNodata: 'There is no match',
        myGamesNodata: 'There is no favorite match',
        statisticNodata: 'There is no statistic information',
        noDataText: 'There is no information',
        matchSet1: '1st Half',
        matchSet2: '2nd Half',
        matchExtra: 'Extra',
        matchInfo: 'Info',
        txtCoins: 'coins',
        txtInfo: 'Info',
        txtLineUp: 'Line-Up',
        txtStatistics: 'Statistics',
        txtTable: 'Table',
        txtReferee: 'Referee',
        txtStadium: 'Stadium',
        txtFormations: 'Formations',
        txtSubstitutions: 'Substitutions',
        txtPrediction: 'Prediction',
        txtSubstitedPlayers: 'Substited Players',
        txtOverall: 'Overall',
        txtHome: 'Home',
        txtAway: 'Away',
        txtTeam: 'Team',
        txtResults: 'Results',
        txtLoadmore: 'Load more',
        txtNotPage404: 'Not Data',
        txtNotTeamHead: 'Not Found',
        txtNotTeamText: 'Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir',
        txtLiveGames: 'Live Games',
        txtFavorite: 'Favorite',
        txtLeagues: 'Leagues',
        txtPrediction: 'Prediction',
        txtSetting: 'Setting',
        txtLanguage: 'Language',
        txtChangeLang: 'Change Language',
        txtCurrentTime: 'Current Time',
        txtMatch: 'Match',
        txtTournament: 'Tournament',
        txtNoAvaible: 'No Avaible For You',
        txtRegisterBtn: 'Register Now',
        txtAll: 'All',
        txtTeams: 'Teams',
        txtCompetitions: 'Competitions',
        txtSingBtn: 'Sign in / up',
        txtEdit: 'Edit',
        txtLogout: 'Logout',
        txtNext: 'Next',
        txtPrHt: 'HT',
        txtPrFt: 'FT',
        txtPrHead: 'Who will win ?',
        txtPrButton: 'Predict',
        txtPrMatchInfo: 'Your Predict Successfully Accepted!',
        txtWin: 'Win',
        txtNew: 'New',
        txtLose: 'Lose',
        txtAmount: 'Amount',
        txtGain: 'Gain',
        txtYes: 'Yes',
        txtNo: 'No',
        txtErrorPhoneNumber: 'Please enter correct Phone number',
        txtNotPredictionMatch: 'You have no match estimates',
        txtPrPageLink: 'All predictions',
        txtCnProdictionHead: 'Cancel Prediction',
        txtCnProdictionText: 'Are you sure that you want to cancel this prediction? <br> You will get only 80% of your points back',
        txtSave: 'Save',
        txtUsername: 'User name',
        txtGooglePlay: 'Download APP from the Playstore.',
        txtRestrictToLogin: 'Please log in to the site',
        txtUsernameUsed: 'This username is used',
        txtSearchPlaceholder: 'Search for',
        txtSubscriptionSystemError: 'Please enter the correct code',
        txtOwnGoal: 'OG',
        txtPenaltyGoal: 'PEN',
        txtTermsAndConditions: 'Terms and conditions',
        txtAllRight: 'All Rights Reserved.',
        txtTermsAndConditions: 'Terms and conditions',
        txtAbout: 'About',
        txtPredictHead: 'Game Predict',
        txtPredictNote: 'Every predict is 500 coins',

    },
    /* English End */

    /* Spanish */
    es: {
        currentTime: 'TIEMPO ACTUAL',
        myTournamentsHead: 'MIS TORNEOS',
        myTournamentsText: 'Para seleccionar tu Liga, nada más haz click aquí <i class="icon icon-top-favourite-selected"></i>  ícono situado al lado del nombre de cada Liga.',
        myTeamsHead: 'MIS EQUIPOS',
        myTeamsText: 'Para seleccionar tu Liga, nada más haz click aquí <i class="icon icon-top-favourite-selected"></i>  ícono situado al lado del nombre de cada equipo.',
        tabAllGames: 'Todos los juegos',
        tabFinished: 'Juegos finalizados',
        tabScheduled: 'Juegos programados',
        tabLive: 'En Vivo',
        tabMyGames: 'Mis Juegos',
        loginGuest: 'Usuario',
        loginButton: 'Login',
        predictionsHead: 'Predicciones',
        footerText: '<p>Las puntuaciones en directo de fútbol en Zunisport tienen cobertura en vivo de más de 500 ligas de fútbol, copas y torneos en todo el mundo, con resultados actualizados en vivo, estadísticas, tablas de ligas, partidos y transmisión en vivo.</p>' +
        '<p>Los partidos en vivo de todas las ligas de fútbol tienen actualizaciones rápidas y precisas de minutos, puntajes, medio tiempo y tiempo completo, marcadores de goles y asistentes, tarjetas, sustituciones, estadísticas de partidos y transmisión en vivo. Zunisport tiene detalles para cada equipo en donde puedes ver los últimos 10 partidos de fútbol, mesas, partidos, resultados, estadísticas y mucho más. Además, todos los puntajes en el puntaje en vivo de Zunisport se actualizan automáticamente y no es necesario actualizarlo manualmente. Con agregar partidos de fútbol o equipos que quieras seguir en favoritos, después de tus partidos o equipos, los puntajes en vivo, los resultados y las estadísticas serán aún más simples. Hay una opción para seleccionar TODOS o Partidos de Fútbol en vivo.</p>',
        portalSelectionHead: 'Seleccioná tu portal',
        month1: 'Enero',
        month2: 'Febrero',
        month3: 'Marzo',
        month4: 'Abril',
        month5: 'Mayo',
        month6: 'Junio',
        month7: 'Julio',
        month8: 'Agosto',
        month9: 'Septiembre',
        month10: 'Octubre',
        month11: 'Noviembre',
        month12: 'Deciembre',
        txtPrNoNewMatch: 'No hay ningún partido nuevo',
        txtPrNoWinMatch: 'No hay ningún partido ganador',
        txtPrNoLoseMatch: 'No hay ningún partido perdido',
        liveNodata: 'No hay ningún partido en vivo',
        matchNodata: 'No hay ningún partido',
        myGamesNodata: 'No hay ningún partido favorito',
        statisticNodata: 'No hay ninguna estadística',
        noDataText: 'No hay información',
        matchSet1: '1era Etapa',
        matchSet2: '2da Etapa',
        matchExtra: 'Extra',
        matchInfo: 'Info',
        txtCoins: 'Monedas',
        txtInfo: 'Info',
        txtLineUp: 'Alineaciones',
        txtStatistics: 'Estadísticas',
        txtTable: 'Tabla',
        txtReferee: 'Referes',
        txtStadium: 'Estadios',
        txtFormations: 'Formaciones',
        txtSubstitutions: 'Cambios',
        txtPrediction: 'Predicción',
        txtSubstitedPlayers: 'Jugadores Suplentes',
        txtOverall: 'En General',
        txtHome: 'Casa',
        txtAway: 'Ausente',
        txtTeam: 'Equipo',
        txtResults: 'Resultados',
        txtLoadmore: 'Cargar Más',
        txtNotPage404: 'Sin Datos',
        txtNotTeamHead: 'No se encuentran datos',
        txtNotTeamText: 'Lorem Ipsum, dizgi ve baskÄ± endÃ¼strisinde kullanÄ±lan mÄ±gÄ±r metinlerdir',
        txtLiveGames: 'Partidos en Vivo',
        txtFavorite: 'Favoritos',
        txtLeagues: 'Ligas',
        txtPrediction: 'Predicciones',
        txtSetting: 'Configuración',
        txtLanguage: 'Idiomas',
        txtChangeLang: 'Cambiar Idiomas',
        txtCurrentTime: 'Tiempo Actual',
        txtMatch: 'Partidos',
        txtTournament: 'Torneos',
        txtNoAvaible: 'No disponible por el momento',
        txtRegisterBtn: 'Registrarse Ahora',
        txtAll: 'Todo',
        txtTeams: 'Equipos',
        txtCompetitions: 'Competencias',
        txtSingBtn: 'Registrarse',
        txtEdit: 'Editar',
        txtLogout: 'Salir',
        txtNext: 'Siguiente',
        txtPrHt: 'HT',
        txtPrFt: 'FT',
        txtPrHead: 'Quien ganará ?',
        txtPrButton: 'Prediccionar',
        txtPrMatchInfo: 'Tu predicción fue aceptada satisfactoriamente!',
        txtWin: 'Ganar',
        txtNew: 'Nuevo',
        txtLose: 'Perdido',
        txtAmount: 'Monto',
        txtGain: 'Ganar',
        txtYes: 'SI',
        txtNo: 'NO',
        txtErrorPhoneNumber: 'Por favor ingresa tu número de teléfono correcto',
        txtNotPredictionMatch: 'No tienes predicciones de partidos',
        txtPrPageLink: 'Todas las predicciones',
        txtCnProdictionHead: 'Cancelar Predicción',
        txtCnProdictionText: 'Estás seguro que quieres cancelar esta predicción? <br> Obtendrás solo el 80% de tus monedas',
        txtSave: 'Salvar',
        txtUsername: 'Nombre de usuario',
        txtGooglePlay: 'Descarga la APP desde el Playstore.',
        txtRestrictToLogin: 'Por favor inicie sesión en el sitio',
    },
    /* Spanish end*/

    /* Azerbaycan */
    aze: {
        currentTime: 'Cari Saat Qurşağı',
        myTournamentsHead: 'Mənim Turnirlərim',
        myTournamentsText: 'Liqanı seçmək üçün, sadəcə <i class="icon icon-top-favourite-selected"></i>  uyğun liqanın yanındakı ulduza tıklayın',
        myTeamsHead: 'Mənim komandalarım',
        myTeamsText: 'Liqanı seçmək üçün, sadəcə <i class="icon icon-top-favourite-selected"></i> uyğun komandanın yanındakı ulduza tıklayın.',
        tabAllGames: 'Bütün oyunlar',
        tabFinished: 'Bitmişlər',
        tabScheduled: 'Cədvəl',
        tabLive: 'Canlı',
        tabMyGames: 'Mənim Oyunlarım',
        loginGuest: 'Qonaq',
        loginButton: 'Qeydiyyat',
        predictionsHead: 'Mərclər',
        footerText: '<p>Football live scores on Zunisport has live coverage from more than 500 worldwide soccer leagues, cups and tournaments with live updated results, statistics, league tables, fixtures and live streaming.</p>' +
        '<p>Live matches from all football leagues have fast and accurate updates for minutes, scores, halftime and full time soccer results, goal scorers and assistants, cards, substitutions, match statistics and live stream. Zunisport has details for each team where you can see last 10 soccer matches, tables, fixtures, results, statistics and much more. Also, all scores on Zunisport livescore are automatically updated and you don\'t need to refresh it manually. With adding football matches or teams you want to follow in favorites, following your matches or teams livescores, results and statistics will be even more simple. There is an option to select All or Live football matches.</p>',
        portalSelectionHead: 'Portalını seç',
        month1: 'Yanvar',
        month2: 'Fevral',
        month3: 'Mart',
        month4: 'Aprel',
        month5: 'May',
        month6: 'İyun',
        month7: 'İyul',
        month8: 'Avqust',
        month9: 'Sentyabr',
        month10: 'Oktyabr',
        month11: 'Noyabr',
        month12: 'Dekabr',
        txtPrNoNewMatch: 'Yeni oyun yoxdur',
        txtPrNoWinMatch: 'Qazanılan oyun yoxdur',
        txtPrNoLoseMatch: 'Uduzulan oyun yoxdur',
        liveNodata: 'Canlı oyun yoxdur',
        matchNodata: 'Oyun yoxdur',
        myGamesNodata: 'Seçilmiş oyun yoxdur',
        statisticNodata: 'Statistik məlumat yoxdur',
        noDataText: 'Məlumat yoxdur',
        matchSet1: '1-inci hissə',
        matchSet2: '2-inci hissə',
        matchExtra: 'Əlavə',
        matchInfo: 'Məlumat',
        txtCoins: 'Jetonlar',
        txtInfo: 'Məlumat',
        txtLineUp: 'Heyət',
        txtStatistics: 'Statistikalar',
        txtTable: 'Cədvəl',
        txtReferee: 'Hakim',
        txtStadium: 'Stadion',
        txtFormations: 'Düzülüş',
        txtSubstitutions: 'Əvəzetmələr',
        txtPrediction: 'Proqnoz',
        txtSubstitedPlayers: 'Əvəzedilən Oyunçular',
        txtOverall: 'Ümumi',
        txtHome: 'Ev',
        txtAway: 'Qonaq',
        txtTeam: 'Komanda',
        txtResults: 'Nəticələr',
        txtLoadmore: 'Daha çox',
        txtNotPage404: 'Məlumat yoxdur',
        txtNotTeamHead: 'Tapılmadı',
        txtNotTeamText: 'Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir',
        txtLiveGames: 'Canlı Oyunlar',
        txtFavorite: 'Seçilmişlər',
        txtLeagues: 'Liqalar',
        txtPrediction: 'Proqnoz',
        txtSetting: 'Tənzimləmələr',
        txtLanguage: 'Dil',
        txtChangeLang: 'Dil seçimi ',
        txtCurrentTime: 'Cari Saat Qurşağı',
        txtMatch: 'Oyun',
        txtTournament: 'Turnir',
        txtNoAvaible: 'Sizinçün əlçatan deyildir',
        txtRegisterBtn: 'Qeydiyyatdan kec',
        txtAll: 'Hamısı',
        txtTeams: 'Komandalar',
        txtCompetitions: 'Yarışlar',
        txtSingBtn: 'Qeydiyyatdan keç',
        txtEdit: 'Dəyiş',
        txtLogout: 'Çıxış',
        txtNext: 'Növbəti',
        txtPrHt: '1-inci hissə',
        txtPrFt: 'Tam hissə',
        txtPrHead: 'Kim qazanacaq?',
        txtPrButton: 'Proqnoz',
        txtPrMatchInfo: 'Sizin mərciniz uğurla tamamlandı!',
        txtWin: 'Qələbə',
        txtNew: 'Yeni',
        txtLose: 'Məğlubiyyət',
        txtAmount: 'Məbləğ',
        txtGain: 'Uduş',
        txtYes: 'Bəli',
        txtNo: 'Xeyr',
        txtErrorPhoneNumber: 'Zəhmət olmazsa düzgün mobil nömrəni daxil edin',
        txtNotPredictionMatch: 'Sizin mərc edilmiş oyununuz yoxdur',
        txtPrPageLink: 'Bütün Proqnozlar',
        txtCnProdictionHead: 'Mərci ləvğ et',
        txtCnProdictionText: 'Mərci ləvğ etmək istədiyinizə əminsiniz? <br> Jetonların 80%-ni geri alacaqsınız',
        txtSave: 'Yadda saxla',
        txtUsername: 'İstifadəçi adı',
        txtGooglePlay: 'Playstore-dan APP-nı yükləyin.',
        txtRestrictToLogin: 'Zəhmət olmasa sayta daxıl olun',
        txtUsernameUsed: 'Bu istifadəçl adı artıq istifadə edilir.',
        txtSearchPlaceholder: 'Axtarış',
        txtSubscriptionSystemError: 'Zəhmət olmasa düzgün kodu girin.',
        txtOwnGoal: 'AQ',
        txtPenaltyGoal: 'PEN',
        txtTermsAndConditions: 'Şərtlər və tələblər',
        txtAllRight: 'Bütün hüquqlar qorunur.',
        txtTermsAndConditions: 'Şərtlər və Qaydalar',
        txtAbout: 'Haqqımızda',
    },
    /* Azerbaycan End */

};

/* Change Language */
function LanguageChange(array) {
    array = array ? array : '';
    if (Language[Help.LangName()]) {
        var LangCode = Help.LangName();
    }
    else {
        var LangCode = 'en';
    }


    var Lists = Language[LangCode];

    if (array.length) {
        array.forEach(function (val) {
            $('[data-lang=' + val + ']').html(Lists[val]);
        });
    }
    else {
        $.each(Lists, function (key, val) {
            $('[data-lang=' + key + ']').html(val);
        });
    }

}

